<?php
/**
 * Created by PhpStorm.
 * User: aiChenK
 * Date: 2020-05-22
 * Time: 14:09
 */

namespace app\api;

use app\BaseController;
use app\middle\Logic;

/**
 * api基础类
 *
 * @author aiChenK
 */
abstract class Base extends BaseController
{
    protected $middleware = [
    ];
    /**
     * @var Logic
     */
    protected $logic;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->logic = new Logic();

    }

    public function setLogic($class, $object = null)
    {
        if ($object && is_object($object)) {
            $this->logic->$class = $object;
        } else {
            $this->logic->$class;
        }
        return $this;
    }
}