<?php
/**
 * Created by PhpStorm.
 * User: aiChenK
 * Date: 2020-05-22
 * Time: 14:09
 */

namespace app\api;

use app\BaseController;
use app\middle\Logic;
use app\middleware\RuleCheck;

/**
 * api基础类
 *
 * @author aiChenK
 */
abstract class Base extends BaseController
{
    protected $middleware = [
        RuleCheck::class
    ];
    /**
     * @var Logic
     */
    protected $logic;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->logic = new Logic();
        $this->logic->setAttrApp($this->app);
        $this->logic->setAttrRequest($this->request);
        $this->logic->initAttrNowTime();
        $this->logic->initAttrLoginInfo();

    }

    public function setLogic($class, $object = null)
    {
        if ($object && is_object($object)) {
            $this->logic->$class = $object;
        } else {
            $this->logic->$class;
        }
        return $this;
    }
}